### ISSUE TITLE
mysql同步至clickhouse，日志出现空指针错误后，数据同步被中断

### ISSUE THREAD

**Issue by Allen0769** [brokercap/Bifrost#241]
**Version:**

 - Bifrost Version: v2.0.6-beta
 - Os Version: CentOS  7
mysql同步至clickhouse的任务中，日志出现空指针错误后，主界面binlog的EventID和position不再刷新，实际数据同步也被中断，但ConnStatus依然是running状态

具体异常日志如下：
`
2023/07/12 07:22:55 channelConsume err: runtime error: invalid memory address or nil pointer dereference goroutine 149 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/brokercap/Bifrost/server.(*Channel).channelConsume.func1()
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel.go:133 +0x45
panic({0x10c00c0, 0x1be4000})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/brokercap/Bifrost/server.(*consume_channel_obj).sendToServerResult(0xc0000d2f68, 0xc000146160, 0xc00097f930)
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel_consume.go:121 +0x465
github.com/brokercap/Bifrost/server.(*consume_channel_obj).sendToServerList0(0xc0000d2f68?, {0xc000012590, 0x1, 0xc0000d2de0?}, 0xc00097f930)
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel_consume.go:307 +0xa9
github.com/brokercap/Bifrost/server.(*consume_channel_obj).sendToServerList(0xc0000d2f68, {0xc005208900?, 0x0?}, 0xc00097f930, 0x1, 0x2d9)
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel_consume.go:264 +0xab
github.com/brokercap/Bifrost/server.(*consume_channel_obj).consumeChannel(0xc0000d2f68)
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel_consume.go:219 +0x3a9
github.com/brokercap/Bifrost/server.(*Channel).channelConsume(0xc000300480)
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel.go:139 +0xad
created by github.com/brokercap/Bifrost/server.(*Channel).Start
        /mnt/hgfs/gopath/src/github.com/brokercap/Bifrost/server/channel.go:91 +0x1b2
`

**Comment by junsonw** [comment]
@Allen0769 哥们 有解决方案吗  我这边也是这样 不知道为什么 你应该是自己捕获了异常吧  我自己加了捕获异常的代码 也发现经常这里会断

**Comment by Allen0769** [comment]
> [@Allen0769](https://github.com/Allen0769) 哥们 有解决方案吗 我这边也是这样 不知道为什么 你应该是自己捕获了异常吧 我自己加了捕获异常的代码 也发现经常这里会断

目前怀疑是数据库链接不稳定(可能是网络原因)导致出现链接断开，但任务无法正常检测，呈现假死状态，我最后没有从代码级别上解决，只是只用定时任务通过调用bifrost的api，监控同步的Chanel状态，一旦出现数据库链接不正常，就调用api对任务进行重启处理，至少解决了自动恢复问题

**Comment by junsonw** [comment]
@Allen0769 我这边几天去研究ToServerInfo.ToServerChan.To <- pluginData 这里 ToServerInfo.ToServerChan.To 这段有时候莫名会变成nil 不确定是不是因为数据库不稳定 断开的情况下 直接把ToServerInfo 赋值为空了 我们之前部署一个项目还好 项目多了这个问题是个大问题 想彻底解决 本地又没办法复现 就算是把数据库断开 恢复 还是可以跑 到了线上不清楚什么原因 或者是网络抖动 几个月一定会来一次

**Comment by Allen0769** [comment]
> [@Allen0769](https://github.com/Allen0769) 我这边几天去研究ToServerInfo.ToServerChan.To <- pluginData 这里 ToServerInfo.ToServerChan.To 这段有时候莫名会变成nil 不确定是不是因为数据库不稳定 断开的情况下 直接把ToServerInfo 赋值为空了 我们之前部署一个项目还好 项目多了这个问题是个大问题 想彻底解决 本地又没办法复现 就算是把数据库断开 恢复 还是可以跑 到了线上不清楚什么原因 或者是网络抖动 几个月一定会来一次

数据库主动断开恢复是没有问题的，但就是链接过程中莫名奇妙的nil导致假死，我们是有其中一个生产上出现这个问题，其它项目上都没遇到过，而且是同样的版本，尝试过升级高版本，也无法解决这个问题，所以当时只能定期监听bifrost的Chanel状态，异常时候重启任务

**Comment by junsonw** [comment]
就是"running","ChannelCount":1这样监控嘛 我准备拿这个做备选方案了 这个莫名其妙的断线 本地没法复现 我只能把锁往下移动了一下 然后select之前在判断一下ToServerInfo.ToServerChan.To整个链子是不是为nil 也不确定解决不解决的到 关键触发也很难触发 比较蛋疼
