### ISSUE TITLE
binlog 不消费,web 后台显示running , log 最后一行显示 已经关闭 mysql 连接

### ISSUE THREAD

**Issue by my943813636** [brokercap/Bifrost#85]
# 日志文件

  | 2020/10/10 02:00:56 jw monitor: parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:00:56 jw monitor: running
root@iZ2vch9tv2s5388awaj4r8Z:~/docker/bifrost# docker-compose logs --tail=100 sync
Attaching to bifrost_sync_1
sync_1        | created by github.com/brokercap/Bifrost/server.(*db).Start
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/server/db.go:467 +0x56e
sync_1        | 
sync_1        | 2020/10/10 02:16:32 jw monitor: parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:32 jw monitor: running
sync_1        | 2020/10/10 02:16:37 jw monitor: starting
sync_1        | 2020/10/10 02:16:37 jw monitor: running
sync_1        | 2020/10/10 02:16:37 binlog_checksum: true
sync_1        | 2020/10/10 02:16:37 root:root@tcp(mysql:3306)/new_julietswhisper  ROTATE_EVENT  mysql-bin.000005 0
sync_1        | 2020/10/10 02:16:37 goroutine 2443 [running]:
sync_1        | runtime/debug.Stack(0xc00036d110, 0x26, 0x0)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/debug/stack.go:24 +0x9d
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2.1(0xc00014fd48)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:578 +0xcb
sync_1        | panic(0xc617e0, 0xc000553ac0)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/panic.go:969 +0x166
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEventRow(0xc0000796c0, 0xc0004f5d10, 0xc0003e11e0, 0xc00034cf40, 0x7, 0x8, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:379 +0x526b
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseRowsEvent(0xc0000796c0, 0xc0004f5d10, 0xe5, 0x10000c0001800f8, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:65 +0x381
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEvent(0xc0000796c0, 0xc0001aaa01, 0x41, 0x41, 0x0, 0x42, 0x0, 0xc0001aaa00, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:181 +0x935
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2(0xc00014fd48, 0xc0000796c0, 0xc0001aaa00, 0x42, 0x42, 0xc00014fd38)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:581 +0xa0
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog(0xc000d157a0, 0xc0001495c0, 0x10, 0x8ec3b3, 0xc0000796c0, 0xc000259330, 0xc00034a300, 0x0, 0x0, 0x0, ...)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:582 +0x3fa
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).startConnAndDumpBinlog(0xc0001ae420, 0xc00034a300)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:863 +0x3d5
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).StartDumpBinlog(0xc0001ae420, 0xc0003575a0, 0x10, 0xca008e4084, 0xc00034a300, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:741 +0x464
sync_1        | created by github.com/brokercap/Bifrost/server.(*db).Start
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/server/db.go:467 +0x56e
sync_1        | 
sync_1        | 2020/10/10 02:16:37 jw monitor: parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:37 jw monitor: running
sync_1        | parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:41 This.mysqlConn close ,connectionId:  329032
sync_1        | 2020/10/10 02:16:42 jw monitor: starting
sync_1        | 2020/10/10 02:16:42 jw monitor: running
sync_1        | 2020/10/10 02:16:42 binlog_checksum: true
sync_1        | 2020/10/10 02:16:42 root:root@tcp(mysql:3306)/new_julietswhisper  ROTATE_EVENT  mysql-bin.000005 0
sync_1        | 2020/10/10 02:16:42 goroutine 2443 [running]:
sync_1        | runtime/debug.Stack(0xc00030e6f0, 0x26, 0x0)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/debug/stack.go:24 +0x9d
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2.1(0xc00014fd48)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:578 +0xcb
sync_1        | panic(0xc617e0, 0xc000ac6660)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/panic.go:969 +0x166
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEventRow(0xc0000796c0, 0xc000411170, 0xc0000cc9a0, 0xc000a3b080, 0x7, 0x8, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:379 +0x526b
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseRowsEvent(0xc0000796c0, 0xc000411170, 0xe5, 0x10000c0001800f8, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:65 +0x381
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEvent(0xc0000796c0, 0xc0002246e1, 0x41, 0x41, 0x0, 0x42, 0x0, 0xc0002246e0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:181 +0x935
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2(0xc00014fd48, 0xc0000796c0, 0xc0002246e0, 0x42, 0x42, 0xc00014fd38)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:581 +0xa0
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog(0xc000d15e60, 0xc0001495c0, 0x10, 0x8ec3b3, 0xc0000796c0, 0xc000259330, 0xc00034a300, 0x0, 0x0, 0x0, ...)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:582 +0x3fa
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).startConnAndDumpBinlog(0xc0001ae420, 0xc00034a300)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:863 +0x3d5
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).StartDumpBinlog(0xc0001ae420, 0xc0003575a0, 0x10, 0xca008e4084, 0xc00034a300, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:741 +0x464
sync_1        | created by github.com/brokercap/Bifrost/server.(*db).Start
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/server/db.go:467 +0x56e
sync_1        | 
sync_1        | 2020/10/10 02:16:42 jw monitor: parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:42 jw monitor: running
sync_1        | parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:47 jw monitor: starting
sync_1        | 2020/10/10 02:16:47 jw monitor: running
sync_1        | 2020/10/10 02:16:47 binlog_checksum: true
sync_1        | 2020/10/10 02:16:47 root:root@tcp(mysql:3306)/new_julietswhisper  ROTATE_EVENT  mysql-bin.000005 0
sync_1        | parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:47 goroutine 2443 [running]:
sync_1        | runtime/debug.Stack(0xc00036dcb0, 0x26, 0x0)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/debug/stack.go:24 +0x9d
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2.1(0xc00014fd48)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:578 +0xcb
sync_1        | panic(0xc617e0, 0xc000037fa0)
sync_1        |         /usr/local/Cellar/go@1.14/1.14.9/libexec/src/runtime/panic.go:969 +0x166
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEventRow(0xc0000796c0, 0xc000469920, 0xc0003e1b80, 0xc00034d280, 0x7, 0x8, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:379 +0x526b
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseRowsEvent(0xc0000796c0, 0xc000469920, 0xe5, 0x10000c0001800f8, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/event_row.go:65 +0x381
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEvent(0xc0000796c0, 0xc0002ff451, 0x41, 0x41, 0x0, 0x42, 0x0, 0xc0002ff450, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:181 +0x935
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2(0xc00014fd48, 0xc0000796c0, 0xc0002ff450, 0x42, 0x42, 0xc00014fd38)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:581 +0xa0
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog(0xc000c1a3c0, 0xc0001495c0, 0x10, 0x8ec3b3, 0xc0000796c0, 0xc000259330, 0xc00034a300, 0x0, 0x0, 0x0, ...)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:582 +0x3fa
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).startConnAndDumpBinlog(0xc0001ae420, 0xc00034a300)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:863 +0x3d5
sync_1        | github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).StartDumpBinlog(0xc0001ae420, 0xc0003575a0, 0x10, 0xca008e4084, 0xc00034a300, 0x0, 0x0, 0x0)
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/Bristol/mysql/binlog.go:741 +0x464
sync_1        | created by github.com/brokercap/Bifrost/server.(*db).Start
sync_1        |         /Users/apple/Desktop/WorkSpae/go/Bifrost/server/db.go:467 +0x56e
sync_1        | 
sync_1        | 2020/10/10 02:16:47 jw monitor: parseEvent err:runtime error: index out of range [-1]
sync_1        | 2020/10/10 02:16:47 jw monitor: running
sync_1        | 2020/10/10 02:16:51 This.mysqlConn close ,connectionId:  329034

# 后台状态

![image](https://user-images.githubusercontent.com/13818013/95643884-c3e02500-0ae4-11eb-8634-a6b170977578.png)

# 补充说明

1. 后台日志显示mysql 断开连接后没有其他日志产生了, 且web后台显示的还是running 状态  (会重新连接, 日志没打印全)
2. binlog 已经不消费了,    **一直重复这个错误 大概15s 出现一次 重启也没用,  除非我跳过这个位点**
3. Bristol/mysql/event_row.go:379 +0x526b 该错误产生频率较高,不太了解mysql binlog 的数据包结构, 这个是属于正常情况吗
5. go version go1.15.2 linux/amd64

**Comment by my943813636** [comment]
找到原因了 , 不可空的枚举类型 为空了
