### ISSUE TITLE
1.5.0-beta1 升级 1.5.0-release 后报错

### ISSUE THREAD

**Issue by lostsnow** [brokercap/Bifrost#87]
mysql aliyun rds 5.7

Bifrost 之前版本是 1.5.0-beta1, 然后升级到1.5.0-release

重启之后手动指定了一次 mysql 的 Position, start 后报错:

```
2020/10/15 11:35:45 clickhouse:......  ROTATE_EVENT  mysql-bin.001002
2020/10/15 11:35:45 goroutine 66 [running]:
runtime/debug.Stack(0xd0ae2c, 0x3d, 0xc00008d8b0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2.1(0xc0006161a0, 0xc00008dd58)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:582 +0x1b3
panic(0xbe9320, 0x1231000)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEvent(0xc0006161a0, 0xc0001c63c1, 0x46, 0x46, 0x0, 0x0, 0x47, 0x0, 0xc0001c63c0)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:204 +0xc37
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2(0xc0006161a0, 0xc00008dd58, 0xc0001c63c0, 0x47, 0x47, 0xc00008dd48)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:585 +0xad
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog(0xc0002c05a0, 0xc00018ef50, 0x10, 0x11152dae, 0xc0006161a0, 0xc0000978e0, 0xc000031920, 0x0, 0x0, 0x0, ...)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:586 +0x425
github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).startConnAndDumpBinlog(0xc0000d6580, 0xc000031920)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:867 +0x3e5
github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).StartDumpBinlog(0xc0000d6580, 0xc000492b40, 0x10, 0x111151c27, 0xc000031920, 0x0, 0x0, 0x0)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:745 +0x452
created by github.com/brokercap/Bifrost/server.(*db).Start
        /root/BifrostBuildSource/v1.5.x/server/db.go:468 +0x5c8

2020/10/15 11:35:45 planet_prod monitor: parseEvent err:err:runtime error: invalid memory address or nil pointer dereference ;lastMapEvent:*mysql.TableMapEvent ;binlogFileName:mysql-bin.001002 ;binlogPosition:286600622
```

之后无论怎么改 position(不管是最新还是旧的), start 也都是同样的错误

然后把 Bifrost 版本降回 1.5.0-beta1, 开启同步, 没有报错

**Comment by lostsnow** [comment]
```
2020/10/16 11:23:13 goroutine 110 [running]:
runtime/debug.Stack(0xd0fae1, 0x54, 0xc0006d3328)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2.1(0xc000220750, 0xc0006d3d58)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:586 +0x1b3
panic(0xc6c760, 0xc0009acf60)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEventRow(0xc000220750, 0xc000732b70, 0xc0006e82c0, 0xc00078b400, 0x48, 0x80, 0x0, 0x0, 0x0)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/event_row.go:379 +0x53b8
github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseRowsEvent(0xc000220750, 0xc000732b70, 0xa129, 0x10000c000496ad8, 0x0)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/event_row.go:65 +0x345
github.com/brokercap/Bifrost/Bristol/mysql.(*eventParser).parseEvent(0xc000220750, 0xc00079b201, 0x119, 0x119, 0x0, 0x0, 0x11a, 0x0, 0xc00079b200)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:189 +0x97e
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog.func2(0xc000220750, 0xc0006d3d58, 0xc00079b200, 0x11a, 0x11a, 0xc0006d3d48)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:589 +0xad
github.com/brokercap/Bifrost/Bristol/mysql.(*mysqlConn).DumpBinlog(0xc0005326c0, 0xc000273320, 0x10, 0xc0ff371, 0xc000220750, 0xc00041cc50, 0xc000610c60, 0x0, 0x0, 0x0, ...)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:590 +0x425
github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).startConnAndDumpBinlog(0xc0000d6630, 0xc000610c60)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:871 +0x3e5
github.com/brokercap/Bifrost/Bristol/mysql.(*BinlogDump).StartDumpBinlog(0xc0000d6630, 0xc00017f660, 0x10, 0x111151c27, 0xc000610c60, 0x0, 0x0, 0xc000000000)
        /root/BifrostBuildSource/v1.5.x/Bristol/mysql/binlog.go:749 +0x452
created by github.com/brokercap/Bifrost/server.(*db).Start
        /root/BifrostBuildSource/v1.5.x/server/db.go:468 +0x5c8

2020/10/16 11:23:13 planet_prod monitor: parseEvent err:parseEvent err recover err:runtime error: index out of range [2] with length 2 ;lastMapEvent:*mysql.TableMapEvent ;binlogFileName:mysql-bin.001006 ;binlogPosition:202371953
```

升级到1.5.1-release 报错如上

**Comment by jc3wish** [comment]
升级到 1.5.2 版本，上述问题都已解决
