### ISSUE TITLE
请选择一个字段为主键！不能保存

### ISSUE THREAD

**Issue by falleafe** [brokercap/Bifrost#92]
mysql同步到mysql设置提交时报错：

2020/11/12 19:00:53 err: interface conversion: driver.Value is uint32, not uint64 goroutine 1280 [running]:
runtime/debug.Stack(0xc00014f778, 0xbf08e0, 0xc0007cc510)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/brokercap/Bifrost/manager/xgo.rounteFunc.func1()
        /root/BifrostBuildSource/v1.5.x/manager/xgo/xgo.go:63 +0x57
panic(0xbf08e0, 0xc0007cc510)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/brokercap/Bifrost/plugin/mysql/src.(*mysqlDB).GetTableFields(0xc00014fbf0, 0xc000810156, 0x4, 0xc000810166, 0xe, 0x0, 0x0, 0x0)
        /root/BifrostBuildSource/v1.5.x/plugin/mysql/src/schema.go:255 +0xb46
github.com/brokercap/Bifrost/plugin/mysql/src.getmysqlTableFields(0xddea20, 0xc00000e080, 0xc0006be500)
        /root/BifrostBuildSource/v1.5.x/plugin/mysql/src/schema.go:67 +0x187
github.com/brokercap/Bifrost/manager/xgo.HandlerFunc.Callback(0xd1a5b0, 0xddea20, 0xc00000e080, 0xc0006be500)
        /root/BifrostBuildSource/v1.5.x/manager/xgo/xgo.go:35 +0x44
github.com/brokercap/Bifrost/manager/xgo.rounteFunc(0xddea20, 0xc00000e080, 0xc0006be500)
        /root/BifrostBuildSource/v1.5.x/manager/xgo/xgo.go:75 +0x1a3
net/http.HandlerFunc.ServeHTTP(0xd1a450, 0xddea20, 0xc00000e080, 0xc0006be500)
        /usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x124bcc0, 0xddea20, 0xc00000e080, 0xc0006be500)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0000ea380, 0xddea20, 0xc00000e080, 0xc0006be500)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.initALPNRequest.ServeHTTP(0xde08a0, 0xc00059b3b0, 0xc00059c380, 0xc0000ea380, 0xddea20, 0xc00000e080, 0xc0006be500)
        /usr/local/go/src/net/http/server.go:3415 +0x8d
net/http.(*http2serverConn).runHandler(0xc000151b00, 0xc00000e080, 0xc0006be500, 0xc000804180)
        /usr/local/go/src/net/http/h2_bundle.go:5718 +0x8b
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5452 +0x505

**Comment by jc3wish** [comment]
请更新升级到当前 v1.5.3-release 或者 v1.6.0-beta.02 版本，此bug已解决

**Comment by jc3wish** [comment]
> 版本2.0.2，2.0.3也报这个错，保存不了，明明选择主键了 但一直提示请选择一个主键 手动填上字段 又提示 选择表

在选择表的时候，不是给打钩，而是点击那个表名 背景为绿色 ，表列表最下面那里，是有 提示的
